# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_HEW2BRzeXyqBL5Tv1WpymhzvluFE-z0
"""

def kasallik(belgi):
  if belgi=="Istima":
    return "parasetamol iching"
  elif belgi=="Bosh og'rig'i":
    return "Bolnol iching"
  elif belgi=="Qorin og'rig'i":
    return "Levomitsin iching"
  elif belgi=="Tish og'rig'i":
    return "Quepen iching"
  else:
    return "Shifokorga murojaat qiling"
belgi=input("Kasallik belgisini kiriting ")
natija=kasallik(belgi)
print(natija)

def meva(nomi):
    if nomi == "Olma":
        return "Olma immunitetni oshiradi"
    elif nomi == "Banan":
        return "Banan energiya beradi"
    elif nomi == "Apelsin":
        return "Apelsin vitamin C ga boy"
    elif nomi == "Uzum":
        return "Uzum qonni tozalaydi"
    elif nomi == "Anor":
        return "Anor qon bosimini me'yorda saqlaydi"
    else:
        return "Bunday meva mavjud emas"

nomi = input("Meva nomini kiriting: ")
natija = meva(nomi)
print(natija)

def talaba(ismi):
    if ismi == "Ali":
        return "Ali 5 baho oldi"
    elif ismi == "Vali":
        return "Vali 4 baho oldi"
    elif ismi == "Sardor":
        return "Sardor 3 baho oldi"
    elif ismi == "Madina":
        return "Madina 5 baho oldi"
    elif ismi == "Dilshod":
        return "Dilshod 4 baho oldi"
    else:
        return "Bunday talaba ro'yxatda yo'q"

ismi = input("Talaba ismini kiriting: ")
natija = talaba(ismi)
print(natija)